---
- name: Install yadm (dotfiles manager)
  ansible.builtin.apt:
    name: yadm
    state: present
  become: true
- name: Check if dotfiles repo already cloned locally
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ yadm_repodir }}"
    clone: no
    update: no
    bare: yes
  register: repo_check
- name: Install dotfiles via yadm
  ansible.builtin.command:
    cmd:  yadm clone "{{ dotfiles_repo }}"
  when: repo_check.before == None
